### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ItsLazer** [BouncyJeffer/SpawnToHub#3]
- [ ] add sendMessage on join (editable)
- [ ] finish off plugin
- [ ] add sound effects on join
